---
apache_listen_port: 80

apache_mods_enabled:
  - rewrite.load
  - alias.load

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"

apache_vhosts:
  - servername: "{{ moodle_wwwroot|regex_replace('^http://', '') }}"
    documentroot: "/var/www/moodle"
