---
- name: Remove install base is it exists
  file: path={{ moodle_location }} state=absent

- name: Make sure the moodle install base is present
  file: 
    path: "{{ moodle_location }}"
    state: directory
    owner:  "{{ apache_user }}"
    group:  "{{ apache_group }}"
    mode:   0755

- name: Make sure we have a moodle data directory
  file:
    path:   "{{ moodle_dataroot }}"
    state:  directory
    owner:  "{{ apache_user }}"
    group:  "{{ apache_group }}"
    mode:   0755
  
- name: Clone the moodle git repo
  git:
    repo: https://github.com/moodle/moodle.git
    dest: "{{ moodle_location }}"
    version: "{{ moodle_tag }}"
    
- name: Remove git folder
  file: path="{{ moodle_location }}/.git" state=absent
  
- name: Remove the moodle database if it exists
  mysql_db: name={{ moodle_db_name }} state=absent
  
- name: Create the moodle database
  mysql_db: name={{ moodle_db_name }} state=present
  
- name: Install Moodle
  sudo: yes
  sudo_user: "{{ apache_user }}"
  command: php admin/cli/install.php \
    --lang=en \
    --wwwroot={{ moodle_wwwroot }} \
    --dataroot={{ moodle_dataroot }} \
    --dbname={{ moodle_db_name }} \
    --dbuser={{ moodle_db_username }} \
    --dbpass={{ moodle_db_password }} \
    --adminuser={{ moodle_adminuser }} \
    --adminpass={{ moodle_adminpass }} \
    {% if moodle_version > 2.8 %}--adminemail='{{ moodle_adminemail }}'{% endif %} \
    --fullname='{{ moodle_fullname }}' \
    --shortname={{ moodle_shortname }} \
    {% if moodle_version > 2.8 %}--summary='{{ moodle_summary }}'{% endif %} \
    --non-interactive \
    --agree-license
  args:
    chdir: "{{ moodle_location }}"
    creates: config.php
