---
# Install prerequisites
- include: prerequisites.yml

# Install Moosh
- include: moosh.yml

# Install Moodle
- include: install.yml

# Install contributed plugins
- include: plugins.yml

# Copy dev plugins to Moodle
- include: plugin_dev.yml

# Apply any patches
- include: patch.yml
