---
- name: Make sure we have a folder to download our plugins to
  file: path=/tmp/moodle-plugins state=directory
  
- name: Download plugins
  get_url:
    url: "{{ item.url }}"
    dest: /tmp/moodle-plugins/{{ item.name }}.zip
  with_items: "{{ moodle_plugins }}"
  
- name: Unzip plugin files
  unarchive:
    copy: no
    src: /tmp/moodle-plugins/{{ item.name }}.zip
    dest: "{{ moodle_location }}/{{ item.destination }}"
    creates: "{{ moodle_location }}/{{ item.destination }}/lib.php"
  with_items: "{{ moodle_plugins }}"
